### ISSUE TITLE
[meta] generating docs

### ISSUE THREAD

**Issue by pq** [monome/dust#105]
meta-issue tracking work around generating docs.

stuff to consider:

* [ ] lua script docs
  * [ ] script tagging (require grid/midi, etc) #104
  * [ ] embedded long-form docs #100
* [ ] sc engine docs
  * [ ] how might `scdoc` and `schelp` fit in?
* [ ] documentation for writing docs (script, module and engine)

also related:

* maiden doc integration (https://github.com/monome/maiden/issues/91)
